#!/bin/bash
/usr/bin/awk ' function GetCellDat(str)
{
	CellStart=RSTART+4
	CellEnd=match(str,/<\/td>/)-8
        Dat=substr(str,CellStart,CellEnd)
        return Dat
}
BEGIN {
	indx=32
	OFS=","
}
{
    if( match($0,/<tr>/) ) {    #ID the start of the relevant data sections
	for(i=0;i<13;i++) {
#	    SET INDEXES INTO CSV TABLE; There are 28 elements, starting at 0
	    if( i==0 ) {   #locale extracted
	 	ref=2
	    }
	    if( i==1 ) {   #hike name
		ref=1
	    }
	    if( i==2 ) {   #wow factor
		ref=11
	    }
	    if( i==3 ) {   #page html file
		ref=27
	    }
	    if( i==5 ) {   #hike length
		ref=7
	    }
	    if( i==6 ) {   #elev change
		ref=8
	    }
	    if( i==7 ) {   #difficulty
		ref=9
	    }
	    if( i==8 ) {   #exposure
		ref=13
	    }
	    if( i==9) {     #map directions
		ref=25
	    }
	    if( i==11) {   #main photo url
		ref=23
	    }
	    getline
#	    GET THE LINE DATA
	    if (i==3) {
		if( match($0,/href/) ) {
			fileStrt=match($0,/\"/)+1
			filenm=substr($0,fileStrt,length)
			fileEnd=match(filenm,/\"/)
			pgFile=substr(filenm,1,fileEnd-1)
			el[ref]=pgFile
		}
	    } else if(i==4) {
#			SKIP THIS LINE
	    } else if(i==8) {
			if( match($0,/sun/) ) {
				expo="sun"
			} else 	if( match($0,/shady/) ) {
					expo="shady"
			} else {
					expo="partial"
			}
			el[13]=expo
	    } else if(i==9) {
			if( match($0,/href/) ) {
				strstrt=match($0,/href/)
				opstr=substr($0,strstrt,length)
				fileStrt=match(opstr,/\"/)+1
                        	filenm=substr(opstr,fileStrt,length)
                        	fileEnd=match(filenm,/\"/)
                        	dirs=substr(filenm,1,fileEnd-1)
				el[ref]=dirs
			}
	    } else if(i==10) {
#			SKIP THIS LINE
	    } else if(i==11) {
			if( match($0,/href/) ) {
                                fileStrt=match($0,/\"/)+1
                                filenm=substr($0,fileStrt,length)
                                fileEnd=match(filenm,/\"/)
                                purl=substr(filenm,1,fileEnd-1)
                                el[ref]=purl
                        }

	    } else if(i==12) {
#			SKIP THIS LINE
	    }
	    else {
		if( match($0,/<td>/) ) {
		    celldat=GetCellDat($0)
		    el[ref]=celldat
		}
	    }
	}
	print indx OFS el[1] OFS el[2] OFS "Normal,,,," el[7] OFS el[8] OFS el[9] OFS OFS el[11] OFS OFS el[13] ",,,,,,,,,," el[23] OFS OFS el[25] OFS OFS el[27]
	indx++
    }   #end if match <td>
} ' hikeDataTbl.html > check	
