#!/bin/bash     
DIR1="accounts"
DIR2="admin"
DIR3="appGpxFiles"
DIR4="data"
DIR5="edit"
DIR6="images"
DIR7="index.html"
#DIR8="ip_files"
DIR9="json"
DIRA="kml"
DIRB="maps"
DIRC="mobile_sass"
DIRD="pages"
DIRE="php"
DIRF="phpseclib1.0.20"
DIRG="sass"
DIRH="scripts"
DIRI="styles"
DIRJ="test"
DIRK="tools"
DIRL="club_assets"
zip -r git_upload.zip "$DIR1" "$DIR2" "$DIR3" "$DIR4" "$DIR5" "$DIR6" "$DIR7" "$DIR9" "$DIRA" "$DIRB" "$DIRC" "$DIRD" "$DIRE" "$DIRF" "$DIRG" "$DIRH" "$DIRI" "$DIRJ" "$DIRK" "$DIRL"
exit 1
